### ISSUE TITLE
Can you provide publisher_non_blocking demo code? 

### ISSUE THREAD

**Issue by hadoopmonica** [videlalvaro/php-amqplib#351]
Can you provide publisher_non_blocking demo code?  Just a simple case, no need for multiple channels.

**Comment by DeeZone** [comment]
Lots of examples to work from on the RabbitMQ site specific to this library and PHP: https://www.rabbitmq.com/tutorials/tutorial-one-php.html

**Comment by hadoopmonica** [comment]
Thanks for your reply, but the link https://github.com/videlalvaro/php-amqplib/blob/master/demo/amqp_publisher.php you gave me is using basic_publish. Is there any way to have non blocking publisher which does not need to wait for the response of basic_publish() method?  You have a demo of non_blocking_consumer as the following link https://github.com/videlalvaro/php-amqplib/blob/master/demo/amqp_consumer_non_blocking.php , can you provide the counterpart of non-blocking publisher demo?

**Comment by DeeZone** [comment]
I might not understand your question but why do you think a `basic_publish()` call would be "blocking"? Take a look at: https://github.com/videlalvaro/php-amqplib/blob/master/demo/amqp_publisher.php All publish calls send a message to an enchange for the time it takes to publish a message. I suspect in the order of nano seconds per call.

Does this address your question?

**Comment by hadoopmonica** [comment]
Thank you for your reply. Because my application needs to handle more than 1000 messages per second, so I need efficient publish mechanism. I observed that the publishing speed cannot handle such speed of messages.

**Comment by DeeZone** [comment]
It's hard to say what the limitation is on your publishing speed but I'm confident there's systems built on top of RabbitMQ that reach/exceed 1000/sec publish rates. I've never been in need of system that exceeds a 500/sec rate but at that rate it was easily accomplished using this library. The success / limitation is the result of system design / architecture rather than the underlying middlewear / hardware.

**Comment by michaelklishin** [comment]
We see a lot of users of this library opening a new connection per *message published*, which is not how messaging protocols are typically meant to be used. 3.6.0 currently has a limit of about 1500 connections accepted/second. We are going to parallelise that in future versions to improve this but the problem is ultimately how the library is used.

1000 messages/second is very doable with any client that maintains a long-lived connection.

**Comment by videlalvaro** [comment]
How do you plan to do that with the PHP execution model where par state
goes away after the request is served? The way to solve that would be to
have some sort of persistent connections, which is not so easy with the
AMQP channel model, when in PHP a persistent connection means the socket
will persist, but not the objects state, like connection and channel.

**Comment by michaelklishin** [comment]
I understand that PHP is, ahem, an interesting language that tied itself for life to a communication model of a single protocol. That does not invalidate the fact that even with a single acceptor per listener in 3.6.0 you can go well above 1000 connections accepted (and thus messages published) per second.

**Comment by videlalvaro** [comment]
Nobody denies what RabbitMQ can achieve, but sadly, this is the reality of
how most people use PHP on the front facing side. So if you need to publish
messages from the Web App Controllers, then unless you achieve some sort of
persistent connection, which as I said, is not easy, then you will end up
with the one message per connection problem.

**Comment by hadoopmonica** [comment]
Yes, thank you!
